node {
    stage ("Checkout DataService"){
        git branch: 'master', url: 'https://github.com/Kmckelle11/MSD-Project.git'
    }
    
    stage ("Gradle Build - DataService") {
	
        sh 'gradle clean build -b spring-boot-project/build.gradle'

    }
    
    stage ("Gradle BootJar-Package - DataService") {
        sh 'gradle bootJar -b spring-boot-project/build.gradle'
    }
    
    stage('User Acceptance Test - DataService') {
	
	  def response= input message: 'Is this build good to go?',
	   parameters: [choice(choices: 'Yes\nNo', 
	   description: '', name: 'Pass')]
	
	  if(response=="Yes") {

	    stage('Release- DataService') {
	     sh 'gradle build -x test'
	     sh 'echo DataService is ready to release!'

	    }
	  }
    }
}
